### ISSUE TITLE
关于裁剪图像

### ISSUE THREAD

**Issue by yayinliqing** [csxmli2016/MARCONet#18]
运行python ./scripts/crop_DF2K时报错，
(marcotrain) shenweilu@node5:~/MARCONet/Train$ python ./scripts/crop_DF2K.py
Traceback (most recent call last):
  File "/home/shenweilu/MARCONet/Train/./scripts/crop_DF2K.py", line 79, in <module>
    SplitNames = os.listdir(TestImgPath)
FileNotFoundError: [Errno 2] No such file or directory: '~/DIV2K_train_HR'
当我把路径改成绝对路径后还是会报错
(marcotrain) shenweilu@node5:~/MARCONet/Train$ python ./scripts/crop_DF2K.py
Traceback (most recent call last):
  File "/home/shenweilu/MARCONet/Train/./scripts/crop_DF2K.py", line 85, in <module>
    KeyLists = os.listdir(osp.join(TestImgPath, split, fi))
NotADirectoryError: [Errno 20] Not a directory: '/home/shenweilu/MARCONet/Train/scripts/DIV2K_train_HR/0759.png'
请告诉我需要裁剪的数据集，我该把数据集放在那里，数据集的结构是怎样的，期待您的回复

**Comment by csxmli2016** [comment]
> 运行python ./scripts/crop_DF2K时报错， (marcotrain) shenweilu@node5:~/MARCONet/Train$ python ./scripts/crop_DF2K.py Traceback (most recent call last): File "/home/shenweilu/MARCONet/Train/./scripts/crop_DF2K.py", line 79, in SplitNames = os.listdir(TestImgPath) FileNotFoundError: [Errno 2] No such file or directory: '~/DIV2K_train_HR' 当我把路径改成绝对路径后还是会报错 (marcotrain) shenweilu@node5:~/MARCONet/Train$ python ./scripts/crop_DF2K.py Traceback (most recent call last): File "/home/shenweilu/MARCONet/Train/./scripts/crop_DF2K.py", line 85, in KeyLists = os.listdir(osp.join(TestImgPath, split, fi)) NotADirectoryError: [Errno 20] Not a directory: '/home/shenweilu/MARCONet/Train/scripts/DIV2K_train_HR/0759.png' 请告诉我需要裁剪的数据集，我该把数据集放在那里，数据集的结构是怎样的，期待您的回复

在代码 ./Train/scripts/crop_DF2K.py 第72到73行，
更改输入路径TestImgPath和保存路径SavePath即可。

**Comment by renjd** [comment]
作者您好，你的合成数据集代码看上去好像是统一图片大小的，那么这种字符较少，右边留黑是预期中的数据吗？

<img width="970" height="59" alt="Image" src="https://github.com/user-attachments/assets/2d7ba23a-a83a-4f23-aeea-54959117a876" />

**Comment by csxmli2016** [comment]
@renjd 没影响，主要用来跟不同字符长度的图片凑成patch，也可以用现有的一些技术每次读取相似宽度的图片。
