### ISSUE TITLE
NameError: name 'fused_act_ext' is not defined

### ISSUE THREAD

**Issue by wuxiaolianggit** [csxmli2016/MARCONet#2]
大佬，您好，运行代码出现：
out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
NameError: name 'fused_act_ext' is not defined

大佬，怎么解决呢？ @csxmli2016

**Comment by chenglih** [comment]
> 可以参考[TencentARC/GFPGAN#5](https://github.com/TencentARC/GFPGAN/issues/5) 安装basicsr 的时候加上
> 
> ```
> BASICSR_EXT=True pip install basicsr
> ```

命令行显示BASICSR_EXT=True不是可执行的命令怎么办

**Comment by yayinliqing** [comment]
> 可以参考[TencentARC/GFPGAN#5](https://github.com/TencentARC/GFPGAN/issues/5) 安装basicsr 的时候加上
> 
> ```
> BASICSR_EXT=True pip install basicsr
> ```

windows 执行不了这个命令啊

**Comment by yayinliqing** [comment]
> > 可以参考[TencentARC/GFPGAN#5](https://github.com/TencentARC/GFPGAN/issues/5) 安装basicsr 的时候加上
> > ```
> > BASICSR_EXT=True pip install basicsr
> > ```
> 
> 命令行显示BASICSR_EXT=True不是可执行的命令怎么办

你解决问题了吗
