### ISSUE TITLE
可以输出预测结果，但没法保存图片，会报错：Error in syn_lq04

### ISSUE THREAD

**Issue by dzyanshan** [csxmli2016/MARCONet#3]
test_sr.py的135行左右，无法通过modelTSPGAN模型正常获取到prior_cha、prior_fea64、prior_fea32导致报错，请问这个是什么原因？

**Comment by csxmli2016** [comment]
> > test_sr.py的135行左右，无法通过modelTSPGAN模型正常获取到prior_cha、prior_fea64、prior_fea32导致报错，请问这个是什么原因？
> 
> 你把异常捕获去掉，看下输出错误是什么，有可能是name 'fused_act_ext' is not defined

我把错信息打印出来了，如果真的是name 'fused_act_ext' is not defined，可以参考https://github.com/TencentARC/GFPGAN/issues/5
这个问题是使用stylegan常见的问题，按照说明安装可以解决。

**Comment by csxmli2016** [comment]
> 十分感谢，是这个问题，成功解决了！另外想请教两个问题，我看到modelTSPGAN模型的输入有label这一项，是因为modelEncoder模型直接输出了低分辨率图像的文本识别结果吗，如果label预测错了那么超分辨率模块难道不会因此输出完全不同的字符吗？

对的。我们的Encoder预测了每个汉字的位置，每个汉字的类别，以及这个片段汉字的字体样式w。我们也给了一个label预测错的结果，https://github.com/csxmli2016/MARCONet#manually-correct-the-text-recognition-results 当退化比较严重的时候，会输出复原错的结果。但是当退化比较轻的时候，这种情况不会依赖label，只是一个简单的SR功能。

**Comment by chenglih** [comment]
> > > test_sr.py的135行左右，无法通过modelTSPGAN模型正常获取到prior_cha、prior_fea64、prior_fea32导致报错，请问这个是什么原因？
> > 
> > 
> > 你把异常捕获去掉，看下输出错误是什么，有可能是name 'fused_act_ext' is not defined
> 
> 我把错信息打印出来了，如果真的是name 'fused_act_ext' is not defined，可以参考[TencentARC/GFPGAN#5](https://github.com/TencentARC/GFPGAN/issues/5) 这个问题是使用stylegan常见的问题，按照说明安装可以解决。

就是BASICSR_EXT=True pip install basicsr 这个命令在windows下好像用不了，该怎么解决呢

**Comment by yayinliqing** [comment]
BASICSR_EXT=True pip install basicsr 这个命令不能运行，会报错'BASICSR_EXT' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
而且也遇到了相同的问题，name 'fused_act_ext' is not defined

**Comment by yayinliqing** [comment]
> > > test_sr.py的135行左右，无法通过modelTSPGAN模型正常获取到prior_cha、prior_fea64、prior_fea32导致报错，请问这个是什么原因？
> > 
> > 
> > 你把异常捕获去掉，看下输出错误是什么，有可能是name 'fused_act_ext' is not defined
> 
> 我把错信息打印出来了，如果真的是name 'fused_act_ext' is not defined，可以参考[TencentARC/GFPGAN#5](https://github.com/TencentARC/GFPGAN/issues/5) 这个问题是使用stylegan常见的问题，按照说明安装可以解决。

还是解决不了这个问题，而且我是window系统，那个命令执行不了啊
