### ISSUE TITLE
Train the model from scratch

### ISSUE THREAD

**Issue by zyzlimit** [csxmli2016/MARCONet#6]
How to train the model from scratch

**Comment by csxmli2016** [comment]
> How to train the model from scratch

Actually, the training process is very complex... I will prepare and release it around this month.

**Comment by csxmli2016** [comment]
> How to train the model from scratch

Hi, we have released all the code. Please refer to https://github.com/csxmli2016/MARCONet/tree/main/Train
Since training from scratch seems very complex, I think the released code can be helpful for you.
